apiVersion: v1
kind: Service

metadata:
  name: {{ .Release.Name }}-ontology-manager

spec:
  type: ClusterIP

  selector:
    app: {{ .Release.Name }}-ontology-manager

  ports:
    - name: http
      port: 8081
      targetPort: 8081