{{- range $name, $user := .Values.users }}
apiVersion: kafka.strimzi.io/v1
kind: KafkaUser
metadata:
  name: {{ $name }}
  labels:
    strimzi.io/cluster: {{ $.Values.kafka.name }}
spec:
  authentication:
    type: {{ $user.authentication.type }}

  {{- if $user.authorization }}
  authorization:
    type: {{ $user.authorization.type }}
    {{- if $user.authorization.acls }}
    acls:
      {{- toYaml $user.authorization.acls | nindent 6 }}
    {{- end }}
  {{- end }}
---
{{- end }}