apiVersion: v1
kind: Secret
metadata:
  name: innet-image-pullsecret  
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "rd-registry.nextworks.it": {
          "username": "<username>",
          "password": "<password>",
        }
      }
    }