mongo:  
  host: mongodb.mongodb.svc.cluster.local
  port: 27017

fillApp:
  image: ghcr.io/intend-project/fill-app:main
  port: 3000

fillDashboard:
  image: ghcr.io/intend-project/fill-frontend:main
  port: 80

# mongoExpress:
#   image: mongo-express:1.0.2-20
#   port: 8081
#   username: admin

fillAgent:
  image: ghcr.io/intend-project/inswitch-agent:main
  port: 8085

fillChat:
  image: ghcr.io/intend-project/inswitch-dashboard:main
  port: 8086

iexplain:
  image: ghcr.io/intend-project/iexplain:sha-4fc942e
  port: 8000

fillSeed:
  image: ghcr.io/intend-project/fill-seed:main
  host: http://fill-app:3000

