apiVersion: v1
kind: Service
metadata:
  name: a2a-registry-worker

spec:
  type: ClusterIP

  selector:
    app: a2a-registry-worker

  ports:
    - name: http
      port: 8000
      targetPort: 8000
      