apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-app  
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: traefik

  tls:
    - hosts:
        - 5g4data-app.intend.dend.ro
      secretName: flask-app-tls

  rules:
    - host: 5g4data-app.intend.dend.ro
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flask-app
                port:
                  number: 5003