apiVersion: v1
kind: Service
metadata:
  name: simulator-agent-kernel

spec:
  type: ClusterIP

  selector:
    app: simulator-agent-kernel

  ports:
    - name: http
      port: "{{ .Values.simulatorAgentKernel.apiServer.port }}"
      targetPort: "{{ .Values.simulatorAgentKernel.apiServer.port }}"