apiVersion: v1
kind: Pod
metadata:
  name: ingraph-pod
  labels:
    app: ingraph
spec:
  containers:
    - name: ingraph
      image: {{ .Values.ingraph.image.repository }}:{{ .Values.ingraph.image.tag }}
      ports:
        - name: ingraph-api
          containerPort: 5000        
      env:
        - name: GRAPHDB_BASE_URL
          value: {{ .Values.ingraph.graphdb.baseUrl }}
        