neo4j:
  disableLookups: true

  neo4j:
    name: neo4j  
    edition: community
    passwordFromSecret: neo4j-auth

  services:
    neo4j:
      spec:
        type: ClusterIP

  # Neo4j listens in plaintext internally
  config:
    dbms.connector.https.enabled: "false"
    dbms.connector.http.enabled: "true"
    dbms.connector.bolt.tls_level: "DISABLED"

  volumes:
    data:
      mode: dynamic
      dynamic:
        storageClassName: block-ssd
        requests:
          storage: 20Gi