apiVersion: apps/v1
kind: Deployment
metadata:
  name: fill-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fill-app
  template:
    metadata:
      labels:
        app: fill-app
    spec:
      initContainers:
        - name: wait-for-mongo
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z {{ .Values.mongo.host }} {{ .Values.mongo.port }}; do
                sleep 5
              done
      containers:
        - name: fill-app
          image: {{ .Values.fillApp.image }}
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_URI
          ports:
            - containerPort: {{ .Values.fillApp.port }}