apiVersion: apps/v1
kind: Deployment
metadata:
  name: iexplain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iexplain
  template:
    metadata:
      labels:
        app: iexplain
    spec:
      containers:
        - name: iexplain
          image: {{ .Values.iexplain.image }}
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: fill-secret
                  key: OPENAI_API_KEY
          ports:
            - containerPort: {{ .Values.iexplain.port }}
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: {{ .Values.iexplain.port }}
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: {{ .Values.iexplain.port }}
            initialDelaySeconds: 10
            periodSeconds: 15