apiVersion: batch/v1
kind: Job
metadata:
  name: fill-seed
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: fill-seed
          image: {{ .Values.fillSeed.image }}
          args:
            - {{ .Values.fillSeed.host | quote }}