apiVersion: batch/v1
kind: Job
metadata:
  name: fill-seed
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: fill-seed
          image: {{ .Values.fillSeed.image }}
          command:
            - python3
            - /app/seed.py
          args:
            - {{ .Values.fillSeed.host | quote }}