apiVersion: v2
name: graphdb
version: 1.0.0
description: Helm chart for deploying GraphDB with ArgoCD
dependencies:
  - name: graphdb
    repository: https://maven.ontotext.com/repository/helm-public/
    version: 12.13.1
