name: inGraph Setup and Test
on: [push, workflow_dispatch]

jobs:
  ingraph-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Clone inGraph repository
        run: git clone https://github.com/INTEND-Project/inGraph.git

      - name: Install dependencies
        run: |
          cd inGraph
          pip install -r requirements.txt

      - name: Start GraphDB
        run: |
          mkdir -p data/conf
          echo "${{ secrets.GRAPHDB_LICENSE_KEY }}" | base64 -d > data/conf/graphdb.license
          docker run -d -p 127.0.0.1:7200:7200 -v $PWD/data:/opt/graphdb/home --name graphdb-instance-name ontotext/graphdb:11.3.1
          for i in {1..30}; do
            if curl -s http://localhost:7200/protocol > /dev/null; then
              echo "GraphDB is up!"
              break
            fi
            echo "Waiting for GraphDB..."
            sleep 5
          done

      - name: Start inGraph
        run: |
          cd inGraph
          python inGraphApp.py &
          for i in {1..20}; do
            if curl -s http://localhost:5000/ > /dev/null; then
              echo "Server is up!"
              break
            fi
            echo "Waiting for server..."
            sleep 2
          done

      - name: Run queries
        run: |
          cd inGraph
          curl -X POST http://localhost:5000/repositories/create -F id=second-graph
          curl -X POST http://localhost:5000/upload -F repository=second-graph -F file=@KG/fillKG.jsonld
          curl -X POST http://localhost:5000/query -F repository=second-graph -F file=@query_test/machine5-query.sparql -F format=json
