strimzi-kafka-operator:
  watchNamespaces:
    - kafka

  replicas: 1

kafka:
  name: kafka
  version: "4.3.1"

  nodePool:
    name: kafka
    replicas: 2

    storage:
      type: persistent-claim
      size: 50Gi
      deleteClaim: false

  listeners:
    - name: authpass
      port: 9092
      type: internal
      tls: true
      authentication:
        type: scram-sha-512
  
  authorization:
    type: simple
    
  config:
    defaultReplicationFactor: 2
    minInsyncReplicas: 1
    offsetsTopicReplicationFactor: 2
    transactionStateLogReplicationFactor: 2
    transactionStateLogMinIsr: 1

topics:
  tasks:
    partitions: 2
    replicas: 1
  responses:
    partitions: 2
    replicas: 1

users:
  operation-manager:
    authentication:
      type: scram-sha-512
    authorization:
      type: simple
      acls:
        - resource:
            type: topic
            name: tasks
            patternType: literal
          operations:
            - Write
            - Describe
        - resource:
            type: topic
            name: responses
            patternType: literal
          operations:
            - Read
            - Describe
        - resource:
            type: group
            name: operation-manager
            patternType: literal
          operations:
            - Read