apiVersion: v1
kind: Service
metadata:
  name: {{ include "fuseki.fullname" . }}
  labels:
    {{- include "fuseki.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "fuseki.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 3030
      protocol: TCP